server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: node3
    prefer-ip-address: true #允许通过设置ip让eureka让其他服务注册它
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.100.101:8761/eureka/